name: CI

on:
  push:
    paths-ignore:
      - 'bench/**'
      - '*.md'
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'bench/**'
      - '*.md'
    branches:
      - master

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [20, 22, 24]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm install

    - name: Type Check
      run: npm run types

    - name: Test
      if: matrix.nodejs < 24
      run: npm test

    - name: Test w/ Coverage
      if: matrix.nodejs >= 24
      run: |
        npm install -g nyc
        nyc --include=src npm test

    - name: Compile
      if: matrix.nodejs >= 24
      run: npm run build

    - name: Report
      if: matrix.nodejs >= 24
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
